config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'#localhosst3000する
  get 'home/about' => 'homes#about'
  get 'users/mypage' => 'users#mypage'
  get 'users/animal/:id' => 'users#animal', as: 'user_animal'
  get '/blog_genre/:id' => 'blogs#genre',as:'blog_genre'#ジャンル検索でidが必要
  get 'search' =>'search#search'
  post 'animals/:animal_id/tasks/:id/change' => 'tasks#change',as: 'task_change'

  resources :users do
    get 'follows' => 'relationships#follows', as: 'follows'#フォロー一覧
    get 'followers' => 'relationships#followers', as: 'followers'#フォロワー一覧
    resource :relationships, only: [:create, :destroy]
    resource :animal_permits, only: [:create, :destroy] do
      patch :status_change#ステータスを変更、animal_permit.rbで指示
    end
  end

  resources :blogs do
  	resource :blog_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :animals do
    resource :animal_comments, only: [:create, :destroy]
    resource :tasks, only: [:create, :destroy, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	has_many :blog_genre_relations
	has_many :genres, through: :blog_genre_relations#中間テーブルを経由して関連づけ
	has_many :blog_comments,dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :blog_image #refile,id入れない
	validates :title, presence: true #空欄NG
	validates :body, presence: true #空欄NG
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

    def Blog.search(search)
           Blog.where(['title LIKE ?', "%#{search}%"])
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :authenticate_user!, only: [:edit, :index, :update, :genre, :destroy, :new, :create]#ログインしていない人をログイン画面へ
before_action :ensure_correct_user, only: [:edit, :update, :destroy]#本人とadmin権限の人しかできないようにする

	def index
		@blogs =Blog.all.order(created_at: :asc).page(params[:page]).reverse_order
    @blog = Blog.new#新規投稿用
    @genres =  Genre.all#ジャンルサイドバー一覧
    #サイドバー
    @user = current_user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
	end

  def genre
    @genres =  Genre.all#ジャンルサイドバー一覧
    @genre = Genre.find(params[:id])# Genreのデータベースのテーブルから一致するidを取得
    @blogs = @genre.blogs.order(created_at: :asc).page(params[:page]).reverse_order# Genreのデータベースのテーブルから取得条件に合致するオブジェクトを配列として取り出す
    @blog = Blog.new#新規投稿用
    #サイドバー
    @user = current_user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
  end

	def show
    @genres =  Genre.all#ジャンルサイドバー一覧
    @blog = Blog.find(params[:id])
    @comment = BlogComment.new#新規コメント空
    @comments = @blog.blog_comments.order(created_at: :asc).page(params[:page]).reverse_order
    #サイドバー
    @user = @blog.user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
	end

  def edit
    @blog = Blog.find(params[:id])
     #サイドバー
    @user = current_user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
    #ジャンルサイドバー一覧
    @genres =  Genre.all
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
       flash[:notice] = "更新しました！"#成功メッセ
       redirect_to blog_path(@blog.id)
    else
      @user = current_user
      @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
      @genres =  Genre.all
      render :edit
    end
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    flash[:notice] = "削除しました"
    redirect_to action: :index
  end

	def new
     #サイドバー
    @user = current_user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
    #ジャンルサイドバー一覧
    @genres =  Genre.all
  	@blog = Blog.new#空のオブジェクト
  end

  def create
  	@blog = Blog.new(blog_params)
  	@blog.user_id = current_user.id #ブログのuser_idカラムにログインしている人のidを送る
  	if @blog.save
  		 flash[:notice] = "投稿しました！"#成功メッセ
  	   redirect_to blog_path(@blog.id)#ブログ詳細
    else
       @user = current_user
       @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
       @genres =  Genre.all
       render :new
    end
  end

  #編集制限
  def ensure_correct_user
    @blog = Blog.find(params[:id])
    if @blog.user != current_user && current_user.admin == 0
      redirect_to blogs_path#移動まえのURL
    end
  end

  	private
  	def blog_params
  		params.require(:blog).permit(:title, :body, :blog_image, genre_ids: [])
  	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/edit.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <!--部分テンプレ-->
      <!--ペット一覧のユーザー-->
      <p><%= render 'layouts/side', user: current_user ,applying: @applying %></p>
      <p><%= render 'layouts/sidegenre', genres: @genres %></p>
    </div>
  </div>

  <!--ブログ新規投稿-->
  <div class="col-xs-9">
    <%= form_for(@blog) do |f| %>
      <%= render 'layouts/error', model: f.object %>
      <p><%= attachment_image_tag @blog, :blog_image, size: "600x520", fallback: "no_image.jpg" %></p>
      <%= f.attachment_field :blog_image %><!-- blog_image_idだがrefileの仕様でidなし --><!-- サイズについての表記を書く -->
      <p>＊印は必ず入力してください</p>
      <h4>タイトル＊</h4>
        <%= f.text_field :title,:size=>"85x1",placeholder: "タイトルを入力してください" %>
      <h4>本文＊</h4>
        <%= f.text_area :body,:size=>"85x10",placeholder: "本文を入力してください" %>
      <h4>ジャンル選択</h4>
        <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
          <%= genre.label {genre.check_box + genre.text } %>
        <% end %>
    <div class="row">
      <div class="col-xs-3 col-xs-offset-3">
        <%= f.submit "投稿",class: "btn btn-warning btn-block" %>
      </div>
    </div>
    <% end %>
 </div>
</div>

app/views/blogs/genre.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <p><%= render 'layouts/side', user: current_user ,applying: @applying %></p>
      <p><%= render 'layouts/sidegenre', genres: @genres %></p>
    </div>
  </div>

  <!--新規投稿-->
  <div class="col-xs-9">
    <% if user_signed_in? %><!-- ログインしている場合に投稿できる -->
      <p><%= link_to new_blog_path do %>
           <%= image_tag "new.png",size: "40x40"%>
         <% end %></p>
    <% end %>

    <!--ブログ一覧、投稿順に並べる-->
    <div class="row">
      <% @blogs.each do |blog| %>
        <div class="blog_index col-xs-3">
          <%= link_to user_path(blog.user.id) do %>
            <%= attachment_image_tag blog.user, :icon, size: "30x30", fallback: "no_image.jpg" %><%= blog.user.name %>
          <% end %><br>
          <%= link_to blog_path(blog.id) do %>
            <%= attachment_image_tag blog, :blog_image,size: "180x180",fallback: "no_image.jpg"%><br>
            <h4><%= blog.title %></h4>
          <% end %>
          <% blog.genres.each do |genre|%><!--登録されているジャンル一覧-->
            <%= link_to blog_genre_path(genre.id),class: "btn btn-default btn-xs" do %>
              <%= genre.name %>
            <% end %>
          <% end %><br>
          <%= blog.created_at.strftime("%Y/%m/%d") %>
          <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: #ef857d;"></span><%= blog.favorites.count %>
          <span class="glyphicon glyphicon-comment" aria-hidden="true" style="color: #82cddd;"></span><%= blog.blog_comments.count %><br>

          <% if blog.user == current_user %><!--本人のみ-->
            <p class="text-right"><%= link_to"edit", edit_blog_path(blog.id) %>
          <% end %>
          <% if blog.user == current_user || current_user.admin? %><!--本人と管理者が可能-->
            <%= link_to"destroy", blog_path(blog.id),method: :delete, data: {confirm: "本当に消しますか？"} %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class ="text-center">
      <%= paginate @blogs %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<!--部分点プレ-->
<!--ペット一覧のユーザー-->
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <%= render 'layouts/side', user: current_user ,applying: @applying %><br>
      <%= render 'layouts/sidegenre', genres: @genres %>
    </div>
  </div>

  <!--新規投稿-->
  <div class="col-xs-9">
    <% if user_signed_in? %><!-- ログインしている場合に投稿できる -->
      <%= link_to new_blog_path do %>
        <%= image_tag "new.png",size: "40x40"%>
      <% end %>
    <% end %><br><br>

    <!--ブログ一覧、投稿順に並べる-->
    <div class="row">
      <% @blogs.each do |blog| %>
        <div class="blog_index col-xs-3">
          <%= link_to user_path(blog.user.id) do %>
            <%= attachment_image_tag blog.user, :icon, size: "30x30", fallback: "no_image.jpg" %><%= blog.user.name %>
          <% end %><br>
          <%= link_to blog_path(blog.id) do %>
            <%= attachment_image_tag blog, :blog_image,size: "180x180",fallback: "no_image.jpg" %><br>
            <h4><%= blog.title %></h4>
          <% end %>
          <% blog.genres.each do |genre|%><!--登録されているジャンル一覧-->
            <%= link_to blog_genre_path(genre.id),class: "btn btn-default btn-xs" do %>
              <%= genre.name %>
            <% end %>
          <% end %><br>
          <%= blog.created_at.strftime("%Y/%m/%d") %>
          <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: #ef857d;"></span><%= blog.favorites.count %>
          <span class="glyphicon glyphicon-comment" aria-hidden="true" style="color: #82cddd;"></span><%= blog.blog_comments.count %><br>

          <% if blog.user == current_user %><!--本人のみ-->
            <p class="text-right"><%= link_to"edit", edit_blog_path(blog.id) %>
          <% end %>
          <% if blog.user == current_user || current_user.admin? %><!--本人と管理者が可能-->
            <%= link_to"destroy", blog_path(blog.id),method: :delete, data: {confirm: "本当に消しますか？"} %></p>
          <% end %>

        </div>
      <% end %>
    </div>
    <div class ="text-center">
      <%= paginate @blogs %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <p><%= render 'layouts/side', user: current_user, applying: @applying %></p>
        <!--ジャンル一覧-->
      <p><%= render 'layouts/sidegenre', genres: @genres %></p>
    </div>
  </div>

    <!--ブログ新規投稿-->
  <div class="col-xs-9">
    <%= form_for(@blog) do |f| %>
      <%= render 'layouts/error', model: f.object %>
      <p><%= attachment_image_tag @blog, :blog_image, size: "600x520", fallback: "no_image.jpg" %></p>
      <%= f.attachment_field :blog_image %><!-- blog_image_idだがrefileの仕様でidなし --><!-- サイズについての表記を書く -->
      <p>＊印は必ず入力してください</p>
      <h4>タイトル＊</h4>
        <%= f.text_field :title,:size=>"85x1",placeholder: "タイトルを入力してください" %>
      <h4>本文＊</h4>
        <%= f.text_area :body,:size=>"85x20",placeholder: "本文を入力してください" %>
      <h4>ジャンル選択</h4>
        <p><%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) do |genre| %>
          <%= genre.label {genre.check_box + genre.text } %>
        <% end %></p>
      <div class="row">
        <div class="col-xs-3 col-xs-offset-3">
          <%= f.submit "投稿",class: "btn btn-warning btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <%= render 'layouts/side', user: @user ,applying: @applying %>
      <%= render 'layouts/sidegenre', genres: @genres %>
    </div>
  </div>

  <!--ブログ詳細-->
  <div class="col-xs-7 col-xs-offset-1">
    <h3><%= @blog.title %></h3>
      <p class="text-right"><%= @blog.created_at.strftime("%Y年%m月%d日") %></p>
    <!--登録されているジャンル一覧-->
    <p><% @blog.genres.each do |genre|%>
      <%= link_to blog_genre_path(genre.id),class: "btn btn-warning" do %>
        <%= genre.name %>
      <% end %>
    <% end %></p>
    <p class="text-center"><%= attachment_image_tag @blog, :blog_image, size: "600x520",fallback: "no_image.jpg",class: "img-responsive" %></p>
    <p><span style="font-size:1.2em;"><%= simple_format(@blog.body) %></span></p>

    <% if user_signed_in? %><!-- ログインしている場合にいいねできる -->
    <!--いいね-->
      <% if @blog.favorited_by?(current_user) %>
        <!--いいねあり、削除リンク-->
        <%= link_to blog_favorites_path(@blog), method: :delete do %>
          <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: #ef857d;"></span><%= @blog.favorites.count %><!--いいねボタン、いいね数-->
        <% end %>
      <% else %>
        <!--いいねなし、追加リンク-->
        <%= link_to blog_favorites_path(@blog), method: :post do %>
          <p><span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span><%= @blog.favorites.count %><!--いいねボタン、いいね数-->
        <% end %>
      <% end %>
      <span class="glyphicon glyphicon-comment" aria-hidden="true" style="color: #82cddd;"></span><%= @blog.blog_comments.count %><!--コメント数--></p>
    <% end %>


    <!--ブログ削除、編集,後で成功、確認メッセとかもいれる-->
    <% if @blog.user == current_user %><!--後々管理者もできるようにする-->
      <p class="text-right"><%= link_to"edit", edit_blog_path(@blog.id) %> /
    <% end %>
    <% if @blog.user == current_user || current_user.admin? %><!--本人と管理者が可能-->
      <%= link_to"delete", blog_path(@blog.id),method: :delete, data: {confirm: "本当に消しますか？"} %></p>
    <% end %>

    <!--コメント投稿-->
    <% if user_signed_in? %><!-- ログインしている場合のみコメントできる -->
      <p><%= form_for [@blog,@comment] do |f| %><!--後々マイページに飛ばす-->
        <%= f.text_area :comment, :size=>"77x3",placeholder: "コメントを入力してください"%>
        <%= f.submit"送信",class: "btn btn-warning btn-xs" %>
      <% end %></p>
    <% end %>

    <!--コメント一覧-->
    <div class="comment_index">
      <div class="row">
        <% @comments.each do |comment| %>
          <div class="col-xs-2">
            <%= link_to user_path(comment.user.id) do %>
              <p><%= attachment_image_tag comment.user, :icon, size: "50x50", fallback: "no_image.jpg" %></p>
              <p><%= comment.user.name %></p>
            <% end %>
          </div>
          <div class="col-xs-9">
            &emsp;<span style="font-size:1.2em;"><%= simple_format(comment.comment) %></span>
            <p class="text-right"><%= comment.user.created_at.strftime("%Y.%m.%d.%H:%M") %></p>
            <% if comment.user_id == current_user.id || current_user.admin? %>
              <p class="text-right"><%= link_to "削除", blog_blog_comments_path(comment.id), method: :delete, data: {confirm: "本当に消しますか？"} %></p>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div class ="text-center">
      <%= paginate @comments %>
    </div>
  </div>
</div>