config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'#localhosst3000する
  get 'home/about' => 'homes#about'
  get 'users/mypage' => 'users#mypage'
  get 'users/animal/:id' => 'users#animal', as: 'user_animal'
  get '/blog_genre/:id' => 'blogs#genre',as:'blog_genre'#ジャンル検索でidが必要
  get 'search' =>'search#search'
  post 'animals/:animal_id/tasks/:id/change' => 'tasks#change',as: 'task_change'

  resources :users do
    get 'follows' => 'relationships#follows', as: 'follows'#フォロー一覧
    get 'followers' => 'relationships#followers', as: 'followers'#フォロワー一覧
    resource :relationships, only: [:create, :destroy]
    resource :animal_permits, only: [:create, :destroy] do
      patch :status_change#ステータスを変更、animal_permit.rbで指示
    end
  end

  resources :blogs do
  	resource :blog_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :animals do
    resource :animal_comments, only: [:create, :destroy]
    resource :tasks, only: [:create, :destroy, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :blogs, dependent: :destroy
  has_many :blog_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :icon#icon_idだがrefileの仕様でidなし
  validates :name,length: {maximum: 10}, presence: true #空欄NG10文字まで

#フォロー機能
  #ユーザーとフォローする人の関連づけ。Relationshipモデルのfollower_idにuser_idを格納
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # 誰かをフォローしている
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #誰かがフォローした人
  #:メソッド、中間テーブルのアソシエーション、sourceでrelationshipのbelongs_toへ
  has_many :following_user, through: :active_relationships, source: :followed #データ先指定
  has_many :follow_user, through: :passive_relationships, source: :follower #データ先指定

#ペット登録
has_many :animals, dependent: :destroy
  has_many :animal_comments, dependent: :destroy#ペットのコメント
# ペット閲覧申請
  #ユーザーとフォローする人の関連づけ
  has_many :active_animal_permits, class_name: "AnimalPermit", foreign_key: "permitter_id", dependent: :destroy # 誰かを許可している人取得
  has_many :passive_animal_permits, class_name: "AnimalPermit", foreign_key: "permitted_id", dependent: :destroy # 誰かが許可した人取得
  #自分がフォローしているユーザーと自分をフォローしているユーザーをとりやすく、中間テーブル
  has_many :permitting_user, through: :active_animal_permits, source: :permitted #データ先指定
  has_many :permitted_user, through: :passive_animal_permits, source: :permitter #データ先指定


#フォローする・フォロー外す・フォローしているか確認を行うメソッドを作成
	# ユーザーをフォローする
	def follow(user_id)
    Relationship.create(follower_id: self.id, followed_id: user_id)#follower_id自分、followerd_idにuser_idをいれる
  end
	#ユーザーのフォローを外す
	def unfollow(user_id)
		Relationship.find_by(follower_id: self.id,followed_id: user_id).destroy
	end
	#フォローしていればtrueを返す
	def following?(user)
		following_user.include?(user)#include配列が val と == で等しい要素を持つ時に真を返します。
	end

#ペット登録
  #許可申請または許可しているか
  def permit(user_id)
    AnimalPermit.create(permitter_id: self.id, permitted_id: user_id)
  end
  #許可申請、許可を外す,flgがownの場合自分からのフォローを消去、otherで他の人が自分をフォローした場合に消去
  def unpermit(user_id, flg)
    if flg == "own"
      AnimalPermit.find_by(permitter_id: self.id, permitted_id: user_id).destroy
    else
      AnimalPermit.find_by(permitter_id: user_id, permitted_id: self.id).destroy
    end
  end
  #閲覧許可申請または閲覧許可していればtrue
  def permitting?(user)
    permitting_user.include?(user)
  end
# 検索
def User.search(search)
 User.where(['name LIKE ?', "%#{search}%"])
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit,:mypage, :update, :destroy, :new, :create, :animal]#ログインしていない人をログイン画面へ
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]#投稿した本人以外できないようにする（管理者もつける）
  #animalページの閲覧制限、不可の場合blog indexへ飛ばす  ページを本人と、ステータスを持った人のみに出したい。他の人はblog index
  before_action :ensure_animal_user, only: [:animal]#ページを（animalページの場合、URLにIDが入っており、そのIDとcurrent_userが同じ場合に表示）


  def index
    @users = User.all.order(created_at: :asc).page(params[:page]).reverse_order
    #サイドバー
    @user = current_user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
  end

  def show#ユーザー情報
    @genres =  Genre.all#ジャンルサイドバー一覧
  	@user = User.find(params[:id])
    @blogs = @user.blogs.order(created_at: :asc).page(params[:page]).reverse_order#うまくいかない
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )#サイドバー
  end
  def edit
    @user = current_user
    @users = AnimalPermit.where(permitted_id: current_user.id, status: 0).order(created_at: :asc).page(params[:page]).reverse_order#申請した人（０）
    @permitted_users = AnimalPermit.where(permitter_id: current_user.id, status: 1).order(created_at: :asc).page(params[:page]).reverse_order#自分をお世話パートナーにしている人
    #サイドバー
    @user = current_user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
  end

  def update
  	@user = current_user
  	if @user.update(user_params)
      flash[:notice] = "更新しました！"#成功メッセ
  	  redirect_to edit_user_path(current_user.id)
    else
      #サイドバー
      @user = current_user
      @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
      @users = AnimalPermit.where(permitted_id: current_user.id, status: 0).order(created_at: :asc).page(params[:page]).reverse_order#申請した人（０）
    @permitted_users = AnimalPermit.where(permitter_id: current_user.id, status: 1).order(created_at: :asc).page(params[:page]).reverse_order#自分をお世話パートナーにしている人
      render :edit
    end
  end
  def destroy
    user = current_user
    user.destroy
    redirect_to root_path
  end
  def animal
    @user = User.find(params[:id])
     #サイドパートナー
    @users = AnimalPermit.where(permitted_id: @user, status: 1).order(created_at: :asc).page(params[:page]).reverse_order#お世話パートナーのサイドバー
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
  end

  #編集制限
  def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to action: :index#一覧へ戻す
    end
  end

  def ensure_animal_user
    @user = User.find(params[:id])
   # p @user.id != current_user.id
    #p AnimalPermit.find_by(permitted_id: current_user.id, status: 1).nil?
    if @user != current_user && AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id, status: 1).nil?
      redirect_to blogs_path#一覧へ戻す
    end
  end

  private
  def user_params
  params.require(:user).permit(:name, :introduction, :icon)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/animal.html.erb
<!--ペット一覧のユーザー-->
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <%= render 'layouts/side', user: @user,applying: @applying %>
      <!--ペット一覧閲覧許可ユーザー-->
      <div class="sidebox">
        <p class="text-center"><span style="font-size:1.3em;">お世話パートナー</span></p>
        <% @users.each do |user| %>
    　    <%= link_to user_path(user.permitter.id),class:"no-underline" do %>
      　    <p class="text-center"><%= attachment_image_tag user.permitter , :icon, size: "80x80", fallback: "no_image.jpg" %></p>
            <p class="text-center"><%= user.permitter.name %></p>
          <% end %>

          <!--削除、user投稿主のみ可能-->
          <% if @user.id == current_user.id %>
    　　     <p class="text-center">
              <%= link_to "パートナー解除", user_animal_permits_path(user_id: user.permitter.id,flg: "other"),class: "btn btn-default btn-xs", method: :delete, data: {confirm: "本当にパートナー解除をしますか？"} %>
            </p>
          <% end %><br>
        <% end %>
      </div>

    </div>
  </div>

  <div class="col-xs-9">
  	<!--本人のみ投稿ボタン-->
  	<% if @user == current_user %><!--animalを投稿した人＝＝ログインしている人だが飛ばない。外部きーのとりかた-->
  	  <%= link_to new_animal_path do %>
        <%= image_tag "new.png",size: "40x40"%>
      <% end %><br>
  	<% end %>
  	<div class="row">
  	  <!--ユーザー一人のペット一覧-->
  	  <% @user.animals.each do |animal| %>
  	    <div class="col-xs-3">
  	      <%= link_to animal_path(animal.id) do %>
  	        <%= attachment_image_tag animal, :animal_image, size: "200x200",fallback: "no_image.jpg",class: "img-circle" %><br><br>
  	        <p class="text-center"><span class="btn btn-warning"><%= animal.name %></span></p><br>
  	      <% end %>
  	    </div>
  	  <% end %>
  	  <div class ="text-center">
  		  <%= paginate @users %>
  	  </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<!-- サイドバー部分テンプレ -->
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <%= render 'layouts/side', user: current_user, applying: @applying %>
    </div>
  </div>
  <!--プロフィール編集-->
  <div class="col-xs-8 col-xs-offset-1">
    <div class="row">
      <h3>プロフィール編集</h3>
       <!--削除ボタン-->
      <div class="col-xs-4">
        <%= link_to "退会",user_path(current_user), method: :delete,class: "btn btn-warning btn-xs", data: {confirm: "本当に退会しますか？"} %><br>
      </div>
    </div>
    <div class="row">
       <%= form_for(@user) do |f|%>
        <div class="row">
          <div class="col-xs-12">
            <%= render 'layouts/error', model: f.object %>
          </div>
        </div>
      <div class="col-xs-4">
        <%= attachment_image_tag @user, :icon, size: "150x150", fallback: "no_image.jpg" %>
        <%= f.attachment_field :icon %><!-- icon_idだがrefileの仕様でidなし -->
      </div>
      <div class="col-xs-4">
        <h4>name(10文字以内)</h4>
          <%= f.text_field :name,:size=>"30x1" %>
        <h4>introduction</h4>
          <%= f.text_area :introduction,:size=>"30x3" %>
        <div class="pull-right">
          <%= f.submit '登録', class: "btn btn-warning" %>
        <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-5">
      <!--お世話申請一覧,自分をフォローしているpermitted_idの人を出す-->
        <h4><p class="text-center">お世話パートナー申請</p></h4>
        <% @users.each do |user| %>
          <%= link_to user_path(user.permitter.id),class:"no-underline" do %>
            <p class="text-center"><%= attachment_image_tag user.permitter , :icon, size: "100x100", fallback: "no_image.jpg" %></p>
          <% end %>
          <%= link_to user_path(user.permitter.id) do %>
            <p class="text-center"><%= user.permitter.name %></p><br>
          <% end %>
          <!--statusを１にするボタン-->
          <div class="pull-right">
            <%= link_to "申請許可", status_change_user_animal_permits_path(user.id),class: "btn btn-default btn-xs", method: :patch, data: {confirm: "本当にパートナーになりますか？"} %>
           <!--フォローを削除するボタン-->
            <%= link_to "申請拒否", user_animal_permits_path(user_id: user.permitter.id, own: "other"),class: "btn btn-default btn-xs", method: :delete, data: {confirm: "本当に拒否しますか？"} %>
          </div>
        <% end %>
        <div class ="text-center">
          <%= paginate @users %>
        </div>
      </div>
      <div class="col-xs-4">
        <!--自分がフォローして,statusが１のリンク,べつページに作る-->
        <h4><p class="text-center">お世話パートナー</p></h4>
        <% @permitted_users.each do |user| %>
          <%= link_to user_path(user.permitted.id),class:"no-underline" do %>
            <p class="text-center"><%= attachment_image_tag user.permitted , :icon, size: "100x100", fallback: "no_image.jpg" %></p>
          <% end %>
          <%= link_to user_path(user.permitted.id) do %>
            <p class="text-center"><%= user.permitted.name %></p>
          <% end %>
        <% end %>
        <div class ="text-center">
          <%= paginate @permitted_users %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <%= render 'layouts/side', user: @user, applying: @applying %>
      <%= render 'layouts/sidegenre', genres: @genres %>
    </div>
  </div>

  <div class="col-xs-9">
    <!--新規投稿-->
    <% if @user.id == current_user.id %><!--本人の場合のみ新規投稿-->
      <p><%= link_to new_blog_path do %>
         <%= image_tag "new.png",size: "40x40"%>
      <% end %></p>
    <% end %>


    <!--ブログ一覧、投稿順に並べる-->
    <div class="row">
      <% @user.blogs.each do |blog| %>
        <div class="blog_index col-xs-3">
          <%= link_to user_path(blog.user.id) do %>
            <p><%= attachment_image_tag blog.user, :icon, size: "30x30", fallback: "no_image.jpg" %><%= blog.user.name %></p>
          <% end %>
          <%= link_to blog_path(blog.id) do %>
            <p><%= attachment_image_tag blog, :blog_image,fallback: "no_image.jpg" %></p>
            <h4><%= blog.title %></h4>
          <% end %>
          <div>
            <% blog.genres.each do |genre|%><!--登録されているジャンル一覧-->
                <%= link_to blog_genre_path(genre.id),class: "btn btn-default btn-xs" do %>
                  <%= genre.name %>
                <% end %>
            <% end %>
          </div>

          <%= blog.created_at.strftime("%Y/%m/%d/%H:%M") %>
          <p><span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: #ef857d;"></span><%= blog.favorites.count %>
          <span class="glyphicon glyphicon-comment" aria-hidden="true" style="color: #82cddd;"></span><%= blog.blog_comments.count %></p>

          <% if blog.user == current_user %><!--本人のみ-->
            <p class="text-right"><%= link_to"edit", edit_blog_path(blog.id) %>
          <% end %>
          <% if blog.user == current_user || current_user.admin? %><!--本人と管理者が可能-->
            <%= link_to"destroy", blog_path(blog.id),method: :delete, data: {confirm: "本当に消しますか？"} %></p>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class ="text-center">
       <%= paginate @blogs %><!--kaminari-->
    </div>
  </div>
</div>