config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'#localhosst3000する
  get 'home/about' => 'homes#about'
  get 'users/mypage' => 'users#mypage'
  get 'users/animal/:id' => 'users#animal', as: 'user_animal'
  get '/blog_genre/:id' => 'blogs#genre',as:'blog_genre'#ジャンル検索でidが必要
  get 'search' =>'search#search'
  post 'animals/:animal_id/tasks/:id/change' => 'tasks#change',as: 'task_change'

  resources :users do
    get 'follows' => 'relationships#follows', as: 'follows'#フォロー一覧
    get 'followers' => 'relationships#followers', as: 'followers'#フォロワー一覧
    resource :relationships, only: [:create, :destroy]
    resource :animal_permits, only: [:create, :destroy] do
      patch :status_change#ステータスを変更、animal_permit.rbで指示
    end
  end

  resources :blogs do
  	resource :blog_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :animals do
    resource :animal_comments, only: [:create, :destroy]
    resource :tasks, only: [:create, :destroy, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
	belongs_to :user
	attachment :animal_image #refile,id入れない
	has_many :animal_comments,-> { order("created_at desc")}, dependent: :destroy#ペットのコメント
	validates :name, presence: true #空欄NG
	has_many :tasks
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!#ログインしていない人をログイン画面へ
  before_action :ensure_correct_user, only: [:destroy]#本人以外できないようにする
  before_action :ensure_animal_user, only: [:show,:edit,:update,:destroy] #ページを本人と、ステータスを持った人のみに出したい。他の人はblog index

  def index
  end

  def show
  	@animal = Animal.find(params[:id])
  	@comment = AnimalComment.new#コメント機能新規
  	@comments = @animal.animal_comments.order(:created_at).page(params[:page]).reverse_order#コメント一覧
    #サイドバー
    @animaluser = @animal.user
    @user = @animal.user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @animaluser.id )
    #お世話パートナーサイドバー
    @pertner = @animal.user.id
    @users = AnimalPermit.where(permitted_id: @pertner, status: 1)#お世話パートナーのサイドバー
    #タスク
    @task = Task.new#タスク新規
    @tasks = @animal.tasks.order(:created_at)#タスク一覧
  end

  def new
  	@animal = Animal.new
    #サイドバー
    @user = current_user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
  end
  def create  #エラー文で使用するので@つける
  	@animal = Animal.new(animal_params)
  	@animal.user_id = current_user.id
  	if @animal.save
      flash[:notice] = "登録しました！"#成功メッセ
  	  redirect_to user_animal_path(current_user.id)#userのanimalページに飛ぶ
    else
      #サイドバー
      @user = current_user
      @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
      render :new
    end
  end

  def edit
  	@animal = Animal.find(params[:id])
    #サイドバー
    @user = current_user
    @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
  end

  def update #エラー文で使用するので@つける
  	@animal = Animal.find(params[:id])
  	if @animal.update(animal_params)
  	  redirect_to action: :show#showへ
    else
      #サイドバー
      @user = current_user
      @applying = AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @user.id )
      render :edit
    end
  end

  def destroy
  	animal = Animal.find(params[:id])
  	animal.destroy
  	redirect_to user_animal_path(current_user.id)#userのanimalページに飛ぶ
  end

  #編集制限
  def ensure_correct_user
    @animal = Animal.find(params[:id])
    if @animal.user_id != current_user.id
      redirect_to blogs_path#一覧へ戻す
    end
  end

    def ensure_animal_user
    @animal = Animal.find(params[:id])
   # p @user.id != current_user.id
    #p AnimalPermit.find_by(permitted_id: current_user.id, status: 1).nil?
    if @animal.user_id != current_user.id && AnimalPermit.find_by(permitter_id: current_user.id, permitted_id: @animal.user_id, status: 1).nil?
      redirect_to blogs_path#一覧へ戻す
    end
  end

  private
  def animal_params
  	params.require(:animal).permit(:animal_image, :name, :birth, :food, :toilet, :water, :hospital, :other)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/edit.html.erb
<div class="row">
    <div class="col-xs-3">
      <div class="row">
        <%= render 'layouts/side', user: current_user, applying: @applying %>
      </div>
    </div>

    <div class="col-xs-8 col-xs-offset-1">
      <div class="row">
        <%= form_for(@animal) do |f| %>
          <%= render 'layouts/error', model: f.object %>
          <div class="col-xs-4">
            <p><%= attachment_image_tag @animal, :animal_image, size: "230x230", fallback: "no_image.jpg" %></p>
            <%= f.attachment_field :animal_image %><!-- blog_image_idだがrefileの仕様でidなし -->
            <p class="text-danger">＊印は必ず入力してください</p>
          </div>

          <div class="col-xs-4">
            <table>
              <tr>
                <th>名前＊</th>
                <td><%= f.text_field :name,:size=>"40x1" %></td>
              </tr>
              <tr>
                <th>birth</th>
                <td><%= raw sprintf(f.date_select(:birth,use_month_numbers: true, start_year: 1950, end_year: Date.today.year,date_separator: '%s'),'年','月')+'日' %></td>
              </tr>
              <tr>
                <th>food</th>
                <td><%= f.text_area :food,:size=>"39x4",placeholder: "例：朝２０g,夜２５g" %></td>
              </tr>
              <tr>
                <th>toilet</th>
                <td><%= f.text_area :toilet,:size=>"39x4",placeholder: "例：毎週火曜日" %></td>
              </tr>
              <tr>
                <th>water</th>
                <td><%= f.text_area :water,:size=>"39x4",placeholder: "例：朝に入れ替え" %></td>
              </tr>
              <tr>
                <th>hospital</th>
                <td><%= f.text_area :hospital,:size=>"39x4",placeholder: "例： ３月に健康診断" %></td>
              </tr>
              <tr>
                <th>other</th>
                <td><%= f.text_area :other,:size=>"39x4" %></td>
              </tr>
            </table>

            <div class="row">
              <div class="col-xs-4 col-xs-offset-12">
                <%= f.submit '登録',class: "btn btn-warning btn-block"%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/animals/new.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <%= render 'layouts/side', user: current_user, applying: @applying %>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-1">
    <div class="row">
      <%= form_for(@animal) do |f| %>
        <%= render 'layouts/error', model: f.object %>
        <div class="col-xs-4">
          <p><%= attachment_image_tag @animal, :animal_image, size: "230x230", fallback: "no_image.jpg" %></p>
          <%= f.attachment_field :animal_image %><!-- blog_image_idだがrefileの仕様でidなし --><!-- サイズについての表記を書く -->
          <p class="text-danger">＊印は必ず入力してください</p>
        </div>
        <div class="col-xs-4">
          <table>
            <tr>
              <th>name＊ </th>
              <td><%= f.text_field :name,:size=>"40x1",placeholder: "お名前" %></td>
            </tr>
            <tr>
              <th>birth </th>
              <td><%= raw sprintf(f.date_select(:birth,use_month_numbers: true, start_year: 1950, end_year: Date.today.year,date_separator: '%s'),'年','月')+'日' %></td>
            </tr>
            <tr>
              <th>food </th>
              <td><%= f.text_area :food,:size=>"39x4",placeholder: "例：朝２０g,夜２５g" %></td>
            </tr>
            <tr>
              <th>toilet </th>
              <td><%= f.text_area :toilet,:size=>"39x4",placeholder: "例：毎週火曜日" %></td>
            </tr>
            <tr>
              <th>water </th>
              <td><%= f.text_area :water,:size=>"39x4",placeholder: "例：朝に入れ替え" %></td>
            </tr>
            <tr>
              <th>hospital </th>
              <td><%= f.text_area :hospital,:size=>"39x4",placeholder: "例： ３月に健康診断" %></td>
            </tr>
            <tr>
              <th>other </th>
              <td><%= f.text_area :other,:size=>"39x4" %></td>
            </tr>
          </table>
            <div class="row">
              <div class="col-xs-4 col-xs-offset-12">
                <%= f.submit "投稿",class: "btn btn-warning btn-block" %>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <div class="row">
      <!--ペット一覧閲覧許可ユーザー-->
      <p><%= render 'layouts/side', user: @animaluser, applying: @applying %></p>
      <p><%= render 'layouts/sidepertners', users: @users, animal: @animal %></p>
    </div>
  </div>
  <!--ペット詳細-->
  <div class="col-xs-6">
    <div class="row">
      <div class="col-xs-4">
        <p><%= attachment_image_tag @animal, :animal_image, size: "150x150",fallback: "no_image.jpg" %></p>
      </div>
      <div class="col-xs-8 table-responsive">
        <table class="table table-bordered animaltable">
          <tbody>
            <tr class="something">
              <th class="warning">名前</th>
              <td class="col-md-10"><%= @animal.name %></td>
            </tr>
            <tr>
               <th class="warning">birth</th>
               <td><%= @animal.birth.strftime("%Y年%m月%d日") %></td>
            </tr>
            <tr>
               <th class="warning">food</th>
               <td><%= simple_format(@animal.food) %></td>
            </tr>
            <tr>
              <th class="warning">toilet</th>
              <td><%= simple_format(@animal.toilet) %></td>
            </tr>
            <tr>
              <th class="warning">water</th>
              <td><%= simple_format(@animal.water) %></td>
            </tr>
            <tr>
              <th class="warning">hospital</th>
              <td><%= simple_format(@animal.hospital) %></td>
            </tr>
            <tr>
              <th class="warning">other</th><td><%= simple_format(@animal.other) %></td>
            </tr>
          </tbody>
        </table><br>
      </div>

      <% if @animal.user == current_user %>
        <p class="text-right">
          <%= link_to "編集", edit_animal_path(@animal.id) %> /
          <%= link_to "削除", animal_path(@animal.id),method: :delete, data: {confirm: "本当に消しますか？"}  %>
        </p>
      <% end %>

      <!--コメント登録-->
      <%= form_for [@animal,@comment] do |f| %>
        <%= render 'layouts/error', model: f.object %>
        <p><%= f.text_area :comment, placeholder:"コメントを入力してください", :size=>"77x3" %></p>
        <div class="col-xs-3 col-xs-offset-11">
            <p><%= f.submit "送信",class: "btn btn-warning btn-xs" %></p>
        </div>
      <% end %>

      <!--コメント一覧-->
      <div class="row">
        <% @animal.animal_comments.each do |animal_comment| %>
          <div class="col-xs-3">
          <%= link_to user_path(animal_comment.user.id) do %><!--ユーザーのshowへ-->
              <%= attachment_image_tag animal_comment.user , :icon, size: "50x50",fallback: "no_image.jpg" %>
          <% end %>
          <%= link_to user_path(animal_comment.user.id) do %>
              <%= animal_comment.user.name %>
          <% end %>
          </div>
          <div class="col-xs-9">
          &emsp;<span style="font-size:1.2em;"><%= simple_format(animal_comment.comment) %></span>
          <p class="text-right"><%= animal_comment.created_at.strftime("%Y-%m-%d %H:%M") %>
          <% if animal_comment.user == current_user %>
              <%= link_to "削除", animal_animal_comments_path(animal_comment.id),method: :delete, data: {confirm: "本当に消しますか？"}  %>
              <% end %></p>
          </div>
        <% end %>
      </div>
    </div>
    <div class ="text-center">
      <%= paginate @comments %>
    </div>
  </div>

  <!--タスク-->
  <div class="col-xs-3">
    <div class="todobox">
      <p class="text-center"><span style="font-size:1.3em;">To Do List</span></p>
      <p><%= form_for [@animal, @task] do |f| %>
        <p><%= f.text_field :content, placeholder:"例：おもちゃを買う" %>
        <%= f.submit"投稿",class: "btn btn-warning btn-xs" %></p>
      <% end %></p>
      <!--タスク一覧-->
      <% @animal.tasks.each do |task|%>
        <span style="font-size:1.1em;"><%= check_box_tag '', '', task.done, {'data-id' => task.id, 'animal_id' => task.animal_id} %><%= task.content %></span><!--id,value必要なし-->
        <a class="no-line"><%= link_to animal_tasks_path(task.id),method: :delete do%>
          <span class="glyphicon glyphicon-remove" aria-hidden="true" style="color: #82cddd;"></span>
        <% end %></a><br>
      <% end %>
    </div>
  </div>

  <!-- jqueryの機能を使ってチェックボックスの制御を行う -->
  <script type="text/javascript"></script>
</div>