config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'#localhosst3000する
  get 'home/about' => 'homes#about'
  get 'users/mypage' => 'users#mypage'
  get 'users/animal/:id' => 'users#animal', as: 'user_animal'
  get '/blog_genre/:id' => 'blogs#genre',as:'blog_genre'#ジャンル検索でidが必要
  get 'search' =>'search#search'
  post 'animals/:animal_id/tasks/:id/change' => 'tasks#change',as: 'task_change'

  resources :users do
    get 'follows' => 'relationships#follows', as: 'follows'#フォロー一覧
    get 'followers' => 'relationships#followers', as: 'followers'#フォロワー一覧
    resource :relationships, only: [:create, :destroy]
    resource :animal_permits, only: [:create, :destroy] do
      patch :status_change#ステータスを変更、animal_permit.rbで指示
    end
  end

  resources :blogs do
  	resource :blog_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :animals do
    resource :animal_comments, only: [:create, :destroy]
    resource :tasks, only: [:create, :destroy, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
	belongs_to :user
	attachment :animal_image #refile,id入れない
	has_many :animal_comments,-> { order("created_at desc")}, dependent: :destroy#ペットのコメント
	validates :name, presence: true #空欄NG
	has_many :tasks
end

app/models/animal_comment.rb
class AnimalComment < ApplicationRecord
	belongs_to :user
	belongs_to :animal
	validates :comment,presence: true #空欄NG
end

app/models/animal_permit.rb
class AnimalPermit < ApplicationRecord
	belongs_to :permitter, class_name: "User"#followerテーブル（user.rbで指定）はないのでUserテーブルを呼ぶよう指定
	belongs_to :permitted, class_name: "User"#followedテーブル（user.rbで指定）はないのでUserテーブルを呼ぶよう指定
#閲覧許可
    enum status:{applying: 0,permit: 1}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	has_many :blog_genre_relations
	has_many :genres, through: :blog_genre_relations#中間テーブルを経由して関連づけ
	has_many :blog_comments,dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :blog_image #refile,id入れない
	validates :title, presence: true #空欄NG
	validates :body, presence: true #空欄NG
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

    def Blog.search(search)
           Blog.where(['title LIKE ?', "%#{search}%"])
    end
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
	belongs_to :blog
	belongs_to :user
	validates :comment, presence: true#コメント空白不可
end

app/models/blog_genre_relation.rb
class BlogGenreRelation < ApplicationRecord
	belongs_to :blog
	belongs_to :genre
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :blog
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :blog_genre_relations
	has_many :blogs, through: :blog_genre_relations #中間テーブルを通して関連づけ
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	#relationshipモデルの
	belongs_to :follower, class_name: "User"#followerテーブル（user.rbで指定）はないのでUserテーブルを呼ぶよう指定
	belongs_to :followed, class_name: "User"#followedテーブル（user.rbで指定）はないのでUserテーブルを呼ぶよう指定
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :animal
	validates :content, presence: true #空欄NG
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :blogs, dependent: :destroy
  has_many :blog_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :icon#icon_idだがrefileの仕様でidなし
  validates :name,length: {maximum: 10}, presence: true #空欄NG10文字まで

#フォロー機能
  #ユーザーとフォローする人の関連づけ。Relationshipモデルのfollower_idにuser_idを格納
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # 誰かをフォローしている
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #誰かがフォローした人
  #:メソッド、中間テーブルのアソシエーション、sourceでrelationshipのbelongs_toへ
  has_many :following_user, through: :active_relationships, source: :followed #データ先指定
  has_many :follow_user, through: :passive_relationships, source: :follower #データ先指定

#ペット登録
has_many :animals, dependent: :destroy
  has_many :animal_comments, dependent: :destroy#ペットのコメント
# ペット閲覧申請
  #ユーザーとフォローする人の関連づけ
  has_many :active_animal_permits, class_name: "AnimalPermit", foreign_key: "permitter_id", dependent: :destroy # 誰かを許可している人取得
  has_many :passive_animal_permits, class_name: "AnimalPermit", foreign_key: "permitted_id", dependent: :destroy # 誰かが許可した人取得
  #自分がフォローしているユーザーと自分をフォローしているユーザーをとりやすく、中間テーブル
  has_many :permitting_user, through: :active_animal_permits, source: :permitted #データ先指定
  has_many :permitted_user, through: :passive_animal_permits, source: :permitter #データ先指定


#フォローする・フォロー外す・フォローしているか確認を行うメソッドを作成
	# ユーザーをフォローする
	def follow(user_id)
    Relationship.create(follower_id: self.id, followed_id: user_id)#follower_id自分、followerd_idにuser_idをいれる
  end
	#ユーザーのフォローを外す
	def unfollow(user_id)
		Relationship.find_by(follower_id: self.id,followed_id: user_id).destroy
	end
	#フォローしていればtrueを返す
	def following?(user)
		following_user.include?(user)#include配列が val と == で等しい要素を持つ時に真を返します。
	end

#ペット登録
  #許可申請または許可しているか
  def permit(user_id)
    AnimalPermit.create(permitter_id: self.id, permitted_id: user_id)
  end
  #許可申請、許可を外す,flgがownの場合自分からのフォローを消去、otherで他の人が自分をフォローした場合に消去
  def unpermit(user_id, flg)
    if flg == "own"
      AnimalPermit.find_by(permitter_id: self.id, permitted_id: user_id).destroy
    else
      AnimalPermit.find_by(permitter_id: user_id, permitted_id: self.id).destroy
    end
  end
  #閲覧許可申請または閲覧許可していればtrue
  def permitting?(user)
    permitting_user.include?(user)
  end
# 検索
def User.search(search)
 User.where(['name LIKE ?', "%#{search}%"])
end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/ _footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>決めてない</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
      <div class='col-xs-3 col-xs-offset-9'>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <%if user_signed_in? %><!-- ログインしているか -->
      <div class="row">
        <div class="center-block" style="width: 400px; text-align: center;">
          <h1>
             <%= link_to blogs_path do%>
               <%= image_tag 'logo.png' %>
             <% end %>
          </h1>
        </div>
      </div>
      <div class="headarea">
        <nav class="navbar">
        <div class="row">
          <div class="center-block" style="width: 360px; text-align: center;">
            <ul class="nav navbar-nav">
              <li><%= link_to"マイページ", edit_user_path(current_user.id) %></li>
              <li><%= link_to"ブログ", blogs_path %></li>
              <li><%= link_to"アバウト", home_about_path %></li>
              <li><%= link_to"ログアウト", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </div>
        </div>
      </div>
         <div class="search-form">
            <div class="row">
              <div class="col-xs-5 col-xs-offset-10">
                <%= form_tag(search_path, method: "get") do %>
                  <%= text_field_tag :search %><!--カラム指定？２つある-->
                  <div class="btn-group">
                    <%= select_tag(:option, options_for_select([["User","1"],["Blog","2"]])) %>
                  </div>
                  <%= submit_tag "検索",class: "btn btn-warning btn-xs" %><!--検索結果表示リンク-->
                <% end %>
              </div><br><br>
            </div>
          </div>
        </nav>

    <% else %>
        <div class="row">
          <div class="center-block" style="width: 400px; text-align: center;">
            <h1>
              <%= link_to root_path do%>
                <%= image_tag 'logo.png' %>
              <% end %>
            </h1>
          </div>
        </div>
        <nav class="navbar">
        <div class="row">
          <div class="center-block" style="width: 258px; text-align: center;">
            <ul class="nav navbar-nav">
              <li><%= link_to"アバウト", home_about_path %></li>
              <li><%= link_to"ログイン", new_user_session_path %></li>
              <li><%= link_to"新規登録", new_user_registration_path %></li>
            </ul>
          </div>
    <% end %>
        </div>
        </nav><br>
  </div>
</header>

app/views/layouts/_side.html.erb
<div>
  <p class="text-center">
  <%= link_to user_path(user) do %>  <!--user＃showへ-->
    <%= attachment_image_tag user, :icon, size: "170x170", fallback: "no_image.jpg",class: "img-circle"%>
  <% end %></p>
  <table class="table">
	  <p class="text-center">
    <tbody>
      <p class="text-center">
        <tr><th>name</th><td><%= user.name %></td></tr>
      </p><!--railsなので％-->
      <p class="text-center">
        <tr><th>introduction</th><td><%= simple_format(user.introduction) %></td></tr>
      </p>
    </tbody></p>
  </table>
  <!--フォローつける-->
  <p class="text-center">
    <%= link_to user.active_relationships.count, user_followers_path(user) %>フォロー
    <%= link_to user.passive_relationships.count, user_followers_path(user) %>フォロワー
  </p>
</div>
<div><!--フォローボタン,ログイン時のみ表示-->
  <% if user_signed_in? %><!-- ログインしているか -->
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <p class="text-center"><%= link_to 'フォローを外す', user_relationships_path(user_id: user.id),class: "btn btn-default", method: :delete %></p>
      <% else %>
　　     <p class="text-center"><%= link_to 'フォローする', user_relationships_path(user_id: user.id),class: "btn btn-warning", method: :post %></p>
      <% end %>
        </p>
    <% end %>
  <% end %>
</div>

<!--お世話記録、ログイン時のみ表示-->
<% if user_signed_in? %><!-- ログインしているか -->
  <!--本人-->
  <% if current_user == user %><!--本人の場合-->
    <p class="text-center">
      <%= link_to "お世話記録",user_animal_path(user.id),class: "btn btn-warning" %>
    </p>
    <p class="text-center">
      <%= link_to "マイページ",edit_user_path(current_user.id),class: "btn btn-warning" %>
    </p>
  <% end %>
  <!--本人以外-->
    <% if current_user != user %>
      <% if current_user.permitting?(user) %><!--申請していてステータス０-->
        <% if applying.status == "applying" %><!--レコードあり、ステータす０-->
          <p class="text-center">お世話パートナー申請中</p>
          <p class="text-center"><%= link_to "申請解除", user_animal_permits_path(user_id: user.id, flg: "own"),class: "btn btn-default",method: :delete, data: {confirm: "本当に解除しますか？"} %></p>
        <% elsif applying.status == "permit" %>
          <p class="text-center">
            <%= link_to "パートナーのお世話記録",user_animal_path(user.id),class: "btn btn-warning" %>
          </p>
          <p class="text-center">
            <%= link_to "パートナー解除",user_animal_permits_path(user_id: user.id,flg: "own"),method: :delete, data: {confirm: "本当に解除しますか？"} %>
          </p>
          <p class="text-center">
            <u>お世話共有申請とは</u>
          </p>
          <p>
            <span style="font-size:0.9em;">飼っているペットのお世話記録を共有します。</span>
          </p>
          <p>
            <span style="font-size:0.9em;">実際にこのユーザーとお世話をしている方のみ申請を行ってください</span>
          </p>
        <% end %>
      <% else %><!--申請していてステータス１-->
        <p class="text-center">
          <%= link_to "お世話パートナー申請", user_animal_permits_path(user_id: user.id),class: "btn btn-default",method: :post %>
        </p>
        <p class="text-center">
          <u>お世話共有申請とは</u>
        </p>
        <p>
          <span style="font-size:0.9em;">飼っているペットのお世話記録を共有します。</span>
        </p>
        <p>
          <span style="font-size:0.9em;">実際にこのユーザーとお世話をしている方のみ申請を行ってください</span>
        </p>
      <% end %>
    <% end %>
  <% end %>

app/views/layouts/_sidegenre.html.erb
<div class="sidegenrebox">
  <div>
	<p class="text-center"><span style="font-size:1.4em;"><u>ジャンル検索</u></span></p>
  </div>
  <div>
	<% genres.each do |genre| %><!--ジャンル一覧、ジャンルテーブルからとってくる-->
	  &emsp;&emsp;&emsp;&emsp;<%= link_to blog_genre_path(genre.id) do %><!-- 投稿一覧リンク（ジャンルidに紐づいてる）-->
	    <span style="font-size:1.1em;"><%= genre.name %></span><br><!--ジャンル名-->
	  <% end %>
	<% end %>
  </div>
</div>

app/views/layouts/_sidepertners.html.erb
<div class="sidebox">
  <p class="text-center"><span style="font-size:1.3em;">お世話パートナー</span></p>

  <% users.each do |user| %>
    <%= link_to user_path(user.permitter.id),class:"no-underline" do %>
      <p class="text-center">
      	<%= attachment_image_tag user.permitter , :icon, size: "80x80", fallback: "no_image.jpg" %>
      </p>
      <p class="text-center">
      	<%= user.permitter.name %>
      </p>
    <% end %>

	<!--削除、user投稿主のみ可能-->
	<% if animal.user_id == current_user.id %>
	  <p class="text-center">
	    <%= link_to "パートナー解除", user_animal_permits_path(user_id: user.permitter.id,flg: "other"),class: "btn btn-default btn-xs", method: :delete, data: {confirm: "本当にパートナー解除をしますか？"} %></p>
	    <% end %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pet</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <%= render 'layouts/header' %>
  <div class="body">
    <div class='container'>

      <p id="notice" style="color: red;"><%= notice %></p><!--メッセ-->

      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>